misc fixes and doc

diff --git a/bin/rdemodel_path b/bin/rdemodel_path
--- a/bin/rdemodel_path
+++ b/bin/rdemodel_path
@@ -26,7 +26,9 @@ while [[ $# -gt 0 ]] ; do
       (-l|--local) mylocal=1;;
       (storage) type=$1;;
       (home) type=$1;;
-      (*) echo "ERROR: Option Not recognized: $1" 1>&2 ; usage_long; exit 1;;
+      (*) if [[ x$1 != x ]] ; then 
+         echo "ERROR: Option Not recognized: $1" 1>&2 ; usage_long; exit 1;
+         fi;;
     esac
     shift
 done
