model_path mode for ignoring SEQ_EXP_HOME for more consistency

diff --git a/bin/rdemodel_path b/bin/rdemodel_path
--- a/bin/rdemodel_path
+++ b/bin/rdemodel_path
@@ -1,12 +1,35 @@
 #!/bin/ksh
 # Return the path to the model directory specified as the argument
 
-# Check for required argument (becomes "type")
-if [[ -z "$1" ]] ; then
-   printf "Usage: $0 [home,storage]\n"
-   exit 1
-fi
-type=$1
+MYSELF=${0##*/}
+DESC='Return the path to the model directory specified as the argument'
+USAGE="Usage: ${MYSELF} [-h] [-l] [storage | home]"
+
+usage_long() {
+	 toto=$(echo -e $USAGE)
+	 more 1>&2 <<EOF
+$DESC
+
+$toto
+
+Options:
+    -h, --help  : print this help
+    -l, --local : for local dir, ignore SEQ_EXP_HOME
+
+EOF
+}
+
+mylocal=0
+while [[ $# -gt 0 ]] ; do
+   case $1 in
+      (-h|--help) usage_long; exit 0;;
+      (-l|--local) mylocal=1;;
+      (storage) type=$1;;
+      (home) type=$1;;
+      (*) echo "ERROR: Option Not recognized: $1" 1>&2 ; usage_long; exit 1;;
+    esac
+    shift
+done
 
 # Check that appropriate env variable is set and valid
 target_base=$(eval echo \$${type}_model)
@@ -20,7 +43,7 @@ if [[ ! -d ${target_base} ]] ; then
 fi
 
 # Create full path name with hash extension for return
-if [[ -n ${SEQ_EXP_HOME} && -d ${SEQ_EXP_HOME} ]] ; then
+if [[ $mylocal == 0 && -n ${SEQ_EXP_HOME} && -d ${SEQ_EXP_HOME} ]] ; then
    mypath=$(true_path ${SEQ_EXP_HOME})
    myname=${SEQ_EXP_HOME##*/}
 else
